name: CI Pipeline - Dev

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  lint-audit-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Audit backend
        run: npm audit --audit-level=high
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      - name: Build backend Docker image
        run: docker build -t zihaobao/backend ./backend
