name: CD Pipeline - Main

on:
  push:
    branches: [main]

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build frontend image
        run: docker build -t zihaobao/app:frontend ./frontend

      - name: Build backend image
        run: docker build -t zihaobao/app:backend ./backend

      - name: Push frontend image
        run: docker push zihaobao/app:frontend

      - name: Push backend image
        run: docker push zihaobao/app:backend
